name: Build Container Image (without pushing)
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@e19285db868b7ebd44ff6b457ba624dec20f5734  # master as of 2022-04-25
      with:
        NO_PUSH: true
